name: Publish frontend

on:
  push:
    tags: ["*"]

jobs:
  publish:
    name: Publish frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install Docker credentials
        run: echo "${APEXAI_CUSTOMER_TOKEN}" | docker login registry-customer.apex.ai -u $ --password-stdin
        env:
          APEXAI_CUSTOMER_TOKEN: "${{ secrets.APEXAI_CUSTOMER_TOKEN }}"
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: frontend
          file: ./frontend/Dockerfile
          push: true
          tags: registry-customer.apex.ai/devops/apex.alan/bb-portal-frontend:${{ github.sha }}
