name: Publish frontend

on:
  push:
    branches: ["main"]

jobs:
  publish:
    name: Publish frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install Docker credentials
        run: echo "${GITHUB_TOKEN}" | docker login ghcr.io -u $ --password-stdin
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/buildbarn/bb-portal-frontend:${{ github.sha }}
